//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18033.
// 
#pragma warning disable 1591

namespace eClass.OtherService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OtherSoap", Namespace="http://police.gov/")]
    public partial class Other : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getNewBNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUrlByFormNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBNoNumberFormattedOperationCompleted;
        
        private System.Threading.SendOrPostCallback convertAsciiToUTFOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBnoIDByCrimeNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCrimeNoByBnoIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBnoIDByBnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBnoIDByBnoHistoryIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getWorkerByWorkHistoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFormattedBnoByBnoIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBnoByBnoIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBnoByBnoHistoryIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckFieldsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UPOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalculateTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSystemDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback convertTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback convertDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCharOperationCompleted;
        
        private System.Threading.SendOrPostCallback mergeDateTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkShiidOgnooOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Other() {
            this.Url = global::eClass.Properties.Settings.Default.eClass_OtherService_Other;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getNewBNoCompletedEventHandler getNewBNoCompleted;
        
        /// <remarks/>
        public event getUrlByFormNameCompletedEventHandler getUrlByFormNameCompleted;
        
        /// <remarks/>
        public event getBNoNumberFormattedCompletedEventHandler getBNoNumberFormattedCompleted;
        
        /// <remarks/>
        public event convertAsciiToUTFCompletedEventHandler convertAsciiToUTFCompleted;
        
        /// <remarks/>
        public event getBnoIDByCrimeNoCompletedEventHandler getBnoIDByCrimeNoCompleted;
        
        /// <remarks/>
        public event getCrimeNoByBnoIDCompletedEventHandler getCrimeNoByBnoIDCompleted;
        
        /// <remarks/>
        public event getBnoIDByBnoCompletedEventHandler getBnoIDByBnoCompleted;
        
        /// <remarks/>
        public event getBnoIDByBnoHistoryIDCompletedEventHandler getBnoIDByBnoHistoryIDCompleted;
        
        /// <remarks/>
        public event getWorkerByWorkHistoryCompletedEventHandler getWorkerByWorkHistoryCompleted;
        
        /// <remarks/>
        public event getFormattedBnoByBnoIDCompletedEventHandler getFormattedBnoByBnoIDCompleted;
        
        /// <remarks/>
        public event getBnoByBnoIDCompletedEventHandler getBnoByBnoIDCompleted;
        
        /// <remarks/>
        public event getBnoByBnoHistoryIDCompletedEventHandler getBnoByBnoHistoryIDCompleted;
        
        /// <remarks/>
        public event CheckFieldsCompletedEventHandler CheckFieldsCompleted;
        
        /// <remarks/>
        public event UPCompletedEventHandler UPCompleted;
        
        /// <remarks/>
        public event CalculateTimeCompletedEventHandler CalculateTimeCompleted;
        
        /// <remarks/>
        public event getSystemDateCompletedEventHandler getSystemDateCompleted;
        
        /// <remarks/>
        public event convertTimeCompletedEventHandler convertTimeCompleted;
        
        /// <remarks/>
        public event convertDateCompletedEventHandler convertDateCompleted;
        
        /// <remarks/>
        public event getCharCompletedEventHandler getCharCompleted;
        
        /// <remarks/>
        public event mergeDateTimeCompletedEventHandler mergeDateTimeCompleted;
        
        /// <remarks/>
        public event checkShiidOgnooCompletedEventHandler checkShiidOgnooCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://police.gov/getNewBNo", RequestNamespace="http://police.gov/", ResponseNamespace="http://police.gov/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getNewBNo(string formName, string WorkHistory_ID, string Year) {
            object[] results = this.Invoke("getNewBNo", new object[] {
                        formName,
                        WorkHistory_ID,
                        Year});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getNewBNoAsync(string formName, string WorkHistory_ID, string Year) {
            this.getNewBNoAsync(formName, WorkHistory_ID, Year, null);
        }
        
        /// <remarks/>
        public void getNewBNoAsync(string formName, string WorkHistory_ID, string Year, object userState) {
            if ((this.getNewBNoOperationCompleted == null)) {
                this.getNewBNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNewBNoOperationCompleted);
            }
            this.InvokeAsync("getNewBNo", new object[] {
                        formName,
                        WorkHistory_ID,
                        Year}, this.getNewBNoOperationCompleted, userState);
        }
        
        private void OngetNewBNoOperationCompleted(object arg) {
            if ((this.getNewBNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNewBNoCompleted(this, new getNewBNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://police.gov/getUrlByFormName", RequestNamespace="http://police.gov/", ResponseNamespace="http://police.gov/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getUrlByFormName(string formName) {
            object[] results = this.Invoke("getUrlByFormName", new object[] {
                        formName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getUrlByFormNameAsync(string formName) {
            this.getUrlByFormNameAsync(formName, null);
        }
        
        /// <remarks/>
        public void getUrlByFormNameAsync(string formName, object userState) {
            if ((this.getUrlByFormNameOperationCompleted == null)) {
                this.getUrlByFormNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUrlByFormNameOperationCompleted);
            }
            this.InvokeAsync("getUrlByFormName", new object[] {
                        formName}, this.getUrlByFormNameOperationCompleted, userState);
        }
        
        private void OngetUrlByFormNameOperationCompleted(object arg) {
            if ((this.getUrlByFormNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUrlByFormNameCompleted(this, new getUrlByFormNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://police.gov/getBNoNumberFormatted", RequestNamespace="http://police.gov/", ResponseNamespace="http://police.gov/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getBNoNumberFormatted(string pBNo) {
            object[] results = this.Invoke("getBNoNumberFormatted", new object[] {
                        pBNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getBNoNumberFormattedAsync(string pBNo) {
            this.getBNoNumberFormattedAsync(pBNo, null);
        }
        
        /// <remarks/>
        public void getBNoNumberFormattedAsync(string pBNo, object userState) {
            if ((this.getBNoNumberFormattedOperationCompleted == null)) {
                this.getBNoNumberFormattedOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBNoNumberFormattedOperationCompleted);
            }
            this.InvokeAsync("getBNoNumberFormatted", new object[] {
                        pBNo}, this.getBNoNumberFormattedOperationCompleted, userState);
        }
        
        private void OngetBNoNumberFormattedOperationCompleted(object arg) {
            if ((this.getBNoNumberFormattedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBNoNumberFormattedCompleted(this, new getBNoNumberFormattedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://police.gov/convertAsciiToUTF", RequestNamespace="http://police.gov/", ResponseNamespace="http://police.gov/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string convertAsciiToUTF(string word) {
            object[] results = this.Invoke("convertAsciiToUTF", new object[] {
                        word});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void convertAsciiToUTFAsync(string word) {
            this.convertAsciiToUTFAsync(word, null);
        }
        
        /// <remarks/>
        public void convertAsciiToUTFAsync(string word, object userState) {
            if ((this.convertAsciiToUTFOperationCompleted == null)) {
                this.convertAsciiToUTFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconvertAsciiToUTFOperationCompleted);
            }
            this.InvokeAsync("convertAsciiToUTF", new object[] {
                        word}, this.convertAsciiToUTFOperationCompleted, userState);
        }
        
        private void OnconvertAsciiToUTFOperationCompleted(object arg) {
            if ((this.convertAsciiToUTFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.convertAsciiToUTFCompleted(this, new convertAsciiToUTFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://police.gov/getBnoIDByCrimeNo", RequestNamespace="http://police.gov/", ResponseNamespace="http://police.gov/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getBnoIDByCrimeNo(string crimeNo) {
            object[] results = this.Invoke("getBnoIDByCrimeNo", new object[] {
                        crimeNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getBnoIDByCrimeNoAsync(string crimeNo) {
            this.getBnoIDByCrimeNoAsync(crimeNo, null);
        }
        
        /// <remarks/>
        public void getBnoIDByCrimeNoAsync(string crimeNo, object userState) {
            if ((this.getBnoIDByCrimeNoOperationCompleted == null)) {
                this.getBnoIDByCrimeNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBnoIDByCrimeNoOperationCompleted);
            }
            this.InvokeAsync("getBnoIDByCrimeNo", new object[] {
                        crimeNo}, this.getBnoIDByCrimeNoOperationCompleted, userState);
        }
        
        private void OngetBnoIDByCrimeNoOperationCompleted(object arg) {
            if ((this.getBnoIDByCrimeNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBnoIDByCrimeNoCompleted(this, new getBnoIDByCrimeNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://police.gov/getCrimeNoByBnoID", RequestNamespace="http://police.gov/", ResponseNamespace="http://police.gov/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCrimeNoByBnoID(string bno_id) {
            object[] results = this.Invoke("getCrimeNoByBnoID", new object[] {
                        bno_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCrimeNoByBnoIDAsync(string bno_id) {
            this.getCrimeNoByBnoIDAsync(bno_id, null);
        }
        
        /// <remarks/>
        public void getCrimeNoByBnoIDAsync(string bno_id, object userState) {
            if ((this.getCrimeNoByBnoIDOperationCompleted == null)) {
                this.getCrimeNoByBnoIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCrimeNoByBnoIDOperationCompleted);
            }
            this.InvokeAsync("getCrimeNoByBnoID", new object[] {
                        bno_id}, this.getCrimeNoByBnoIDOperationCompleted, userState);
        }
        
        private void OngetCrimeNoByBnoIDOperationCompleted(object arg) {
            if ((this.getCrimeNoByBnoIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCrimeNoByBnoIDCompleted(this, new getCrimeNoByBnoIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://police.gov/getBnoIDByBno", RequestNamespace="http://police.gov/", ResponseNamespace="http://police.gov/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getBnoIDByBno(string bno) {
            object[] results = this.Invoke("getBnoIDByBno", new object[] {
                        bno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getBnoIDByBnoAsync(string bno) {
            this.getBnoIDByBnoAsync(bno, null);
        }
        
        /// <remarks/>
        public void getBnoIDByBnoAsync(string bno, object userState) {
            if ((this.getBnoIDByBnoOperationCompleted == null)) {
                this.getBnoIDByBnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBnoIDByBnoOperationCompleted);
            }
            this.InvokeAsync("getBnoIDByBno", new object[] {
                        bno}, this.getBnoIDByBnoOperationCompleted, userState);
        }
        
        private void OngetBnoIDByBnoOperationCompleted(object arg) {
            if ((this.getBnoIDByBnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBnoIDByBnoCompleted(this, new getBnoIDByBnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://police.gov/getBnoIDByBnoHistoryID", RequestNamespace="http://police.gov/", ResponseNamespace="http://police.gov/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getBnoIDByBnoHistoryID(string bnoHistoryID) {
            object[] results = this.Invoke("getBnoIDByBnoHistoryID", new object[] {
                        bnoHistoryID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getBnoIDByBnoHistoryIDAsync(string bnoHistoryID) {
            this.getBnoIDByBnoHistoryIDAsync(bnoHistoryID, null);
        }
        
        /// <remarks/>
        public void getBnoIDByBnoHistoryIDAsync(string bnoHistoryID, object userState) {
            if ((this.getBnoIDByBnoHistoryIDOperationCompleted == null)) {
                this.getBnoIDByBnoHistoryIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBnoIDByBnoHistoryIDOperationCompleted);
            }
            this.InvokeAsync("getBnoIDByBnoHistoryID", new object[] {
                        bnoHistoryID}, this.getBnoIDByBnoHistoryIDOperationCompleted, userState);
        }
        
        private void OngetBnoIDByBnoHistoryIDOperationCompleted(object arg) {
            if ((this.getBnoIDByBnoHistoryIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBnoIDByBnoHistoryIDCompleted(this, new getBnoIDByBnoHistoryIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://police.gov/getWorkerByWorkHistory", RequestNamespace="http://police.gov/", ResponseNamespace="http://police.gov/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getWorkerByWorkHistory(string workHistoryID, string type) {
            object[] results = this.Invoke("getWorkerByWorkHistory", new object[] {
                        workHistoryID,
                        type});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getWorkerByWorkHistoryAsync(string workHistoryID, string type) {
            this.getWorkerByWorkHistoryAsync(workHistoryID, type, null);
        }
        
        /// <remarks/>
        public void getWorkerByWorkHistoryAsync(string workHistoryID, string type, object userState) {
            if ((this.getWorkerByWorkHistoryOperationCompleted == null)) {
                this.getWorkerByWorkHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetWorkerByWorkHistoryOperationCompleted);
            }
            this.InvokeAsync("getWorkerByWorkHistory", new object[] {
                        workHistoryID,
                        type}, this.getWorkerByWorkHistoryOperationCompleted, userState);
        }
        
        private void OngetWorkerByWorkHistoryOperationCompleted(object arg) {
            if ((this.getWorkerByWorkHistoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getWorkerByWorkHistoryCompleted(this, new getWorkerByWorkHistoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://police.gov/getFormattedBnoByBnoID", RequestNamespace="http://police.gov/", ResponseNamespace="http://police.gov/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getFormattedBnoByBnoID(string bnoID) {
            object[] results = this.Invoke("getFormattedBnoByBnoID", new object[] {
                        bnoID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getFormattedBnoByBnoIDAsync(string bnoID) {
            this.getFormattedBnoByBnoIDAsync(bnoID, null);
        }
        
        /// <remarks/>
        public void getFormattedBnoByBnoIDAsync(string bnoID, object userState) {
            if ((this.getFormattedBnoByBnoIDOperationCompleted == null)) {
                this.getFormattedBnoByBnoIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFormattedBnoByBnoIDOperationCompleted);
            }
            this.InvokeAsync("getFormattedBnoByBnoID", new object[] {
                        bnoID}, this.getFormattedBnoByBnoIDOperationCompleted, userState);
        }
        
        private void OngetFormattedBnoByBnoIDOperationCompleted(object arg) {
            if ((this.getFormattedBnoByBnoIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFormattedBnoByBnoIDCompleted(this, new getFormattedBnoByBnoIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://police.gov/getBnoByBnoID", RequestNamespace="http://police.gov/", ResponseNamespace="http://police.gov/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getBnoByBnoID(string bnoID) {
            object[] results = this.Invoke("getBnoByBnoID", new object[] {
                        bnoID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getBnoByBnoIDAsync(string bnoID) {
            this.getBnoByBnoIDAsync(bnoID, null);
        }
        
        /// <remarks/>
        public void getBnoByBnoIDAsync(string bnoID, object userState) {
            if ((this.getBnoByBnoIDOperationCompleted == null)) {
                this.getBnoByBnoIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBnoByBnoIDOperationCompleted);
            }
            this.InvokeAsync("getBnoByBnoID", new object[] {
                        bnoID}, this.getBnoByBnoIDOperationCompleted, userState);
        }
        
        private void OngetBnoByBnoIDOperationCompleted(object arg) {
            if ((this.getBnoByBnoIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBnoByBnoIDCompleted(this, new getBnoByBnoIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://police.gov/getBnoByBnoHistoryID", RequestNamespace="http://police.gov/", ResponseNamespace="http://police.gov/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getBnoByBnoHistoryID(string bnoHistoryID) {
            object[] results = this.Invoke("getBnoByBnoHistoryID", new object[] {
                        bnoHistoryID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getBnoByBnoHistoryIDAsync(string bnoHistoryID) {
            this.getBnoByBnoHistoryIDAsync(bnoHistoryID, null);
        }
        
        /// <remarks/>
        public void getBnoByBnoHistoryIDAsync(string bnoHistoryID, object userState) {
            if ((this.getBnoByBnoHistoryIDOperationCompleted == null)) {
                this.getBnoByBnoHistoryIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBnoByBnoHistoryIDOperationCompleted);
            }
            this.InvokeAsync("getBnoByBnoHistoryID", new object[] {
                        bnoHistoryID}, this.getBnoByBnoHistoryIDOperationCompleted, userState);
        }
        
        private void OngetBnoByBnoHistoryIDOperationCompleted(object arg) {
            if ((this.getBnoByBnoHistoryIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBnoByBnoHistoryIDCompleted(this, new getBnoByBnoHistoryIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://police.gov/CheckFields", RequestNamespace="http://police.gov/", ResponseNamespace="http://police.gov/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckFields(int start, int end, string[] flds) {
            object[] results = this.Invoke("CheckFields", new object[] {
                        start,
                        end,
                        flds});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckFieldsAsync(int start, int end, string[] flds) {
            this.CheckFieldsAsync(start, end, flds, null);
        }
        
        /// <remarks/>
        public void CheckFieldsAsync(int start, int end, string[] flds, object userState) {
            if ((this.CheckFieldsOperationCompleted == null)) {
                this.CheckFieldsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckFieldsOperationCompleted);
            }
            this.InvokeAsync("CheckFields", new object[] {
                        start,
                        end,
                        flds}, this.CheckFieldsOperationCompleted, userState);
        }
        
        private void OnCheckFieldsOperationCompleted(object arg) {
            if ((this.CheckFieldsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckFieldsCompleted(this, new CheckFieldsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://police.gov/UP", RequestNamespace="http://police.gov/", ResponseNamespace="http://police.gov/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UP(string text) {
            object[] results = this.Invoke("UP", new object[] {
                        text});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UPAsync(string text) {
            this.UPAsync(text, null);
        }
        
        /// <remarks/>
        public void UPAsync(string text, object userState) {
            if ((this.UPOperationCompleted == null)) {
                this.UPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUPOperationCompleted);
            }
            this.InvokeAsync("UP", new object[] {
                        text}, this.UPOperationCompleted, userState);
        }
        
        private void OnUPOperationCompleted(object arg) {
            if ((this.UPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UPCompleted(this, new UPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://police.gov/CalculateTime", RequestNamespace="http://police.gov/", ResponseNamespace="http://police.gov/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CalculateTime(string start, string end) {
            object[] results = this.Invoke("CalculateTime", new object[] {
                        start,
                        end});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CalculateTimeAsync(string start, string end) {
            this.CalculateTimeAsync(start, end, null);
        }
        
        /// <remarks/>
        public void CalculateTimeAsync(string start, string end, object userState) {
            if ((this.CalculateTimeOperationCompleted == null)) {
                this.CalculateTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculateTimeOperationCompleted);
            }
            this.InvokeAsync("CalculateTime", new object[] {
                        start,
                        end}, this.CalculateTimeOperationCompleted, userState);
        }
        
        private void OnCalculateTimeOperationCompleted(object arg) {
            if ((this.CalculateTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculateTimeCompleted(this, new CalculateTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://police.gov/getSystemDate", RequestNamespace="http://police.gov/", ResponseNamespace="http://police.gov/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime getSystemDate() {
            object[] results = this.Invoke("getSystemDate", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void getSystemDateAsync() {
            this.getSystemDateAsync(null);
        }
        
        /// <remarks/>
        public void getSystemDateAsync(object userState) {
            if ((this.getSystemDateOperationCompleted == null)) {
                this.getSystemDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSystemDateOperationCompleted);
            }
            this.InvokeAsync("getSystemDate", new object[0], this.getSystemDateOperationCompleted, userState);
        }
        
        private void OngetSystemDateOperationCompleted(object arg) {
            if ((this.getSystemDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSystemDateCompleted(this, new getSystemDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://police.gov/convertTime", RequestNamespace="http://police.gov/", ResponseNamespace="http://police.gov/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string convertTime(System.DateTime date) {
            object[] results = this.Invoke("convertTime", new object[] {
                        date});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void convertTimeAsync(System.DateTime date) {
            this.convertTimeAsync(date, null);
        }
        
        /// <remarks/>
        public void convertTimeAsync(System.DateTime date, object userState) {
            if ((this.convertTimeOperationCompleted == null)) {
                this.convertTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconvertTimeOperationCompleted);
            }
            this.InvokeAsync("convertTime", new object[] {
                        date}, this.convertTimeOperationCompleted, userState);
        }
        
        private void OnconvertTimeOperationCompleted(object arg) {
            if ((this.convertTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.convertTimeCompleted(this, new convertTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://police.gov/convertDate", RequestNamespace="http://police.gov/", ResponseNamespace="http://police.gov/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string convertDate(System.DateTime date) {
            object[] results = this.Invoke("convertDate", new object[] {
                        date});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void convertDateAsync(System.DateTime date) {
            this.convertDateAsync(date, null);
        }
        
        /// <remarks/>
        public void convertDateAsync(System.DateTime date, object userState) {
            if ((this.convertDateOperationCompleted == null)) {
                this.convertDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconvertDateOperationCompleted);
            }
            this.InvokeAsync("convertDate", new object[] {
                        date}, this.convertDateOperationCompleted, userState);
        }
        
        private void OnconvertDateOperationCompleted(object arg) {
            if ((this.convertDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.convertDateCompleted(this, new convertDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://police.gov/getChar", RequestNamespace="http://police.gov/", ResponseNamespace="http://police.gov/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getChar(System.DateTime date) {
            object[] results = this.Invoke("getChar", new object[] {
                        date});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCharAsync(System.DateTime date) {
            this.getCharAsync(date, null);
        }
        
        /// <remarks/>
        public void getCharAsync(System.DateTime date, object userState) {
            if ((this.getCharOperationCompleted == null)) {
                this.getCharOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCharOperationCompleted);
            }
            this.InvokeAsync("getChar", new object[] {
                        date}, this.getCharOperationCompleted, userState);
        }
        
        private void OngetCharOperationCompleted(object arg) {
            if ((this.getCharCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCharCompleted(this, new getCharCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://police.gov/mergeDateTime", RequestNamespace="http://police.gov/", ResponseNamespace="http://police.gov/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime mergeDateTime(System.DateTime date, System.DateTime time) {
            object[] results = this.Invoke("mergeDateTime", new object[] {
                        date,
                        time});
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void mergeDateTimeAsync(System.DateTime date, System.DateTime time) {
            this.mergeDateTimeAsync(date, time, null);
        }
        
        /// <remarks/>
        public void mergeDateTimeAsync(System.DateTime date, System.DateTime time, object userState) {
            if ((this.mergeDateTimeOperationCompleted == null)) {
                this.mergeDateTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmergeDateTimeOperationCompleted);
            }
            this.InvokeAsync("mergeDateTime", new object[] {
                        date,
                        time}, this.mergeDateTimeOperationCompleted, userState);
        }
        
        private void OnmergeDateTimeOperationCompleted(object arg) {
            if ((this.mergeDateTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mergeDateTimeCompleted(this, new mergeDateTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://police.gov/checkShiidOgnoo", RequestNamespace="http://police.gov/", ResponseNamespace="http://police.gov/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool checkShiidOgnoo(string M1100_ID, System.DateTime date, ref string message, string workHistoryID) {
            object[] results = this.Invoke("checkShiidOgnoo", new object[] {
                        M1100_ID,
                        date,
                        message,
                        workHistoryID});
            message = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void checkShiidOgnooAsync(string M1100_ID, System.DateTime date, string message, string workHistoryID) {
            this.checkShiidOgnooAsync(M1100_ID, date, message, workHistoryID, null);
        }
        
        /// <remarks/>
        public void checkShiidOgnooAsync(string M1100_ID, System.DateTime date, string message, string workHistoryID, object userState) {
            if ((this.checkShiidOgnooOperationCompleted == null)) {
                this.checkShiidOgnooOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckShiidOgnooOperationCompleted);
            }
            this.InvokeAsync("checkShiidOgnoo", new object[] {
                        M1100_ID,
                        date,
                        message,
                        workHistoryID}, this.checkShiidOgnooOperationCompleted, userState);
        }
        
        private void OncheckShiidOgnooOperationCompleted(object arg) {
            if ((this.checkShiidOgnooCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkShiidOgnooCompleted(this, new checkShiidOgnooCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getNewBNoCompletedEventHandler(object sender, getNewBNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNewBNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNewBNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getUrlByFormNameCompletedEventHandler(object sender, getUrlByFormNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUrlByFormNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUrlByFormNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getBNoNumberFormattedCompletedEventHandler(object sender, getBNoNumberFormattedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBNoNumberFormattedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBNoNumberFormattedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void convertAsciiToUTFCompletedEventHandler(object sender, convertAsciiToUTFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class convertAsciiToUTFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal convertAsciiToUTFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getBnoIDByCrimeNoCompletedEventHandler(object sender, getBnoIDByCrimeNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBnoIDByCrimeNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBnoIDByCrimeNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getCrimeNoByBnoIDCompletedEventHandler(object sender, getCrimeNoByBnoIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCrimeNoByBnoIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCrimeNoByBnoIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getBnoIDByBnoCompletedEventHandler(object sender, getBnoIDByBnoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBnoIDByBnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBnoIDByBnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getBnoIDByBnoHistoryIDCompletedEventHandler(object sender, getBnoIDByBnoHistoryIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBnoIDByBnoHistoryIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBnoIDByBnoHistoryIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getWorkerByWorkHistoryCompletedEventHandler(object sender, getWorkerByWorkHistoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getWorkerByWorkHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getWorkerByWorkHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getFormattedBnoByBnoIDCompletedEventHandler(object sender, getFormattedBnoByBnoIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFormattedBnoByBnoIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFormattedBnoByBnoIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getBnoByBnoIDCompletedEventHandler(object sender, getBnoByBnoIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBnoByBnoIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBnoByBnoIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getBnoByBnoHistoryIDCompletedEventHandler(object sender, getBnoByBnoHistoryIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBnoByBnoHistoryIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBnoByBnoHistoryIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CheckFieldsCompletedEventHandler(object sender, CheckFieldsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckFieldsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckFieldsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UPCompletedEventHandler(object sender, UPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CalculateTimeCompletedEventHandler(object sender, CalculateTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculateTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculateTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getSystemDateCompletedEventHandler(object sender, getSystemDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSystemDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSystemDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void convertTimeCompletedEventHandler(object sender, convertTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class convertTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal convertTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void convertDateCompletedEventHandler(object sender, convertDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class convertDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal convertDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getCharCompletedEventHandler(object sender, getCharCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCharCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCharCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void mergeDateTimeCompletedEventHandler(object sender, mergeDateTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mergeDateTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mergeDateTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void checkShiidOgnooCompletedEventHandler(object sender, checkShiidOgnooCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkShiidOgnooCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkShiidOgnooCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591