//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (Japan).
        /// </summary>
        internal static string AddressJapan {
            get {
                return ResourceManager.GetString("AddressJapan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (Mongolia).
        /// </summary>
        internal static string AddressMongolia {
            get {
                return ResourceManager.GetString("AddressMongolia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese auto parts delivery service.
        /// </summary>
        internal static string AutoParts {
            get {
                return ResourceManager.GetString("AutoParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstly, You need to register in website.  Next to fill your all package&apos;s information..
        /// </summary>
        internal static string BriefGuideLine {
            get {
                return ResourceManager.GetString("BriefGuideLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator of package fee.
        /// </summary>
        internal static string Calculation {
            get {
                return ResourceManager.GetString("Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangePackageInformation.
        /// </summary>
        internal static string ChangePackageInformation {
            get {
                return ResourceManager.GetString("ChangePackageInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change personal information.
        /// </summary>
        internal static string ChangeUserInformation {
            get {
                return ResourceManager.GetString("ChangeUserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation.
        /// </summary>
        internal static string ConfirmationPassword {
            get {
                return ResourceManager.GetString("ConfirmationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created User.
        /// </summary>
        internal static string CreatedUser {
            get {
                return ResourceManager.GetString("CreatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your e-mail address is not registered in Tabi.mn.
        /// </summary>
        internal static string EmailNotRegistered {
            get {
                return ResourceManager.GetString("EmailNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty list.
        /// </summary>
        internal static string Emptylist {
            get {
                return ResourceManager.GetString("Emptylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter correct value.
        /// </summary>
        internal static string EnterCorrectValue {
            get {
                return ResourceManager.GetString("EnterCorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter correct e-mail address.
        /// </summary>
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter items.
        /// </summary>
        internal static string EnterItems {
            get {
                return ResourceManager.GetString("EnterItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value.
        /// </summary>
        internal static string EnterValue {
            get {
                return ResourceManager.GetString("EnterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill following information.
        /// </summary>
        internal static string FillFollowingInformation {
            get {
                return ResourceManager.GetString("FillFollowingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese fish, seafoods delivery service.
        /// </summary>
        internal static string FishService {
            get {
                return ResourceManager.GetString("FishService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use.
        /// </summary>
        internal static string Guideline {
            get {
                return ResourceManager.GetString("Guideline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Japan to Mongolia in SEVEN days.
        /// </summary>
        internal static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string ItemBrand {
            get {
                return ResourceManager.GetString("ItemBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string ItemCount {
            get {
                return ResourceManager.GetString("ItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item name.
        /// </summary>
        internal static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount.
        /// </summary>
        internal static string ItemTotalPrice {
            get {
                return ResourceManager.GetString("ItemTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit price.
        /// </summary>
        internal static string ItemUnitPrice {
            get {
                return ResourceManager.GetString("ItemUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese online shopping sites guideline.
        /// </summary>
        internal static string JapanShopping {
            get {
                return ResourceManager.GetString("JapanShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 5 package.
        /// </summary>
        internal static string Last5Package {
            get {
                return ResourceManager.GetString("Last5Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login.
        /// </summary>
        internal static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Section.
        /// </summary>
        internal static string LoginSection {
            get {
                return ResourceManager.GetString("LoginSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent password reset request to your e-mail. Please check Spam and Junk folder of your e-mail inbox..
        /// </summary>
        internal static string MessageSentReset {
            get {
                return ResourceManager.GetString("MessageSentReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to TaBi.
        /// </summary>
        internal static string MessageWelcome {
            get {
                return ResourceManager.GetString("MessageWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new parcel.
        /// </summary>
        internal static string NewPackage {
            get {
                return ResourceManager.GetString("NewPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onnetsu therapy.
        /// </summary>
        internal static string Onnetsu {
            get {
                return ResourceManager.GetString("Onnetsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver name.
        /// </summary>
        internal static string OrderCustomer {
            get {
                return ResourceManager.GetString("OrderCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number.
        /// </summary>
        internal static string OrderNo {
            get {
                return ResourceManager.GetString("OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order amount.
        /// </summary>
        internal static string OrderTotalAmount {
            get {
                return ResourceManager.GetString("OrderTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Number.
        /// </summary>
        internal static string OrderTrackingNo {
            get {
                return ResourceManager.GetString("OrderTrackingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order website.
        /// </summary>
        internal static string OrderWebSite {
            get {
                return ResourceManager.GetString("OrderWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Service.
        /// </summary>
        internal static string OtherService {
            get {
                return ResourceManager.GetString("OtherService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcel.
        /// </summary>
        internal static string Package {
            get {
                return ResourceManager.GetString("Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcel calculation.
        /// </summary>
        internal static string PackageCalc {
            get {
                return ResourceManager.GetString("PackageCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel package.
        /// </summary>
        internal static string PackageCancellation {
            get {
                return ResourceManager.GetString("PackageCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcel status.
        /// </summary>
        internal static string PackageCheckStatus {
            get {
                return ResourceManager.GetString("PackageCheckStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comfirm package.
        /// </summary>
        internal static string PackageConfirmation {
            get {
                return ResourceManager.GetString("PackageConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcel general information.
        /// </summary>
        internal static string PackageDescription {
            get {
                return ResourceManager.GetString("PackageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Information.
        /// </summary>
        internal static string PackageInformation {
            get {
                return ResourceManager.GetString("PackageInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrated parcels.
        /// </summary>
        internal static string PackageList {
            get {
                return ResourceManager.GetString("PackageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver name at Mongolia.
        /// </summary>
        internal static string PackageReciever {
            get {
                return ResourceManager.GetString("PackageReciever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcel regisration.
        /// </summary>
        internal static string PackageRegister {
            get {
                return ResourceManager.GetString("PackageRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Status.
        /// </summary>
        internal static string PackageStatus {
            get {
                return ResourceManager.GetString("PackageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackageTabiNo.
        /// </summary>
        internal static string PackageTabiNo {
            get {
                return ResourceManager.GetString("PackageTabiNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All parcels.
        /// </summary>
        internal static string PackageTotal {
            get {
                return ResourceManager.GetString("PackageTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Fee.
        /// </summary>
        internal static string PackageTransportFee {
            get {
                return ResourceManager.GetString("PackageTransportFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcel shipping user.
        /// </summary>
        internal static string PackageUser {
            get {
                return ResourceManager.GetString("PackageUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Volume.
        /// </summary>
        internal static string PackageVolume {
            get {
                return ResourceManager.GetString("PackageVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Weight.
        /// </summary>
        internal static string PackageWeight {
            get {
                return ResourceManager.GetString("PackageWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone (Japan).
        /// </summary>
        internal static string PhoneJapan {
            get {
                return ResourceManager.GetString("PhoneJapan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone (Mongolia).
        /// </summary>
        internal static string PhoneMongolia {
            get {
                return ResourceManager.GetString("PhoneMongolia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver address at Mongolia.
        /// </summary>
        internal static string RecieverAddress {
            get {
                return ResourceManager.GetString("RecieverAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver phone number at Mongolia.
        /// </summary>
        internal static string RecieverPhone {
            get {
                return ResourceManager.GetString("RecieverPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabi.mn Password reset.
        /// </summary>
        internal static string ResetPasswordEmailSubject {
            get {
                return ResourceManager.GetString("ResetPasswordEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received password reset request. Please visit following link.
        /// </summary>
        internal static string ResetPasswordHtml {
            get {
                return ResourceManager.GetString("ResetPasswordHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales tax.
        /// </summary>
        internal static string SalesTax {
            get {
                return ResourceManager.GetString("SalesTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our service.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        internal static string Shipping {
            get {
                return ResourceManager.GetString("Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of service.
        /// </summary>
        internal static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal information.
        /// </summary>
        internal static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string UserRegister {
            get {
                return ResourceManager.GetString("UserRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaBi.mn Japan-Mongolia package delivery service center.
        /// </summary>
        internal static string WebTitle {
            get {
                return ResourceManager.GetString("WebTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
